name: Swift

on: [push]

jobs:
  macos:
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: Homebrew/actions/git-ssh@master
      with:
        git_user: BastianInuk
        git_email: bastian@inuk.blog
        key_name: key_rsa
        key: ${{ secrets.SSH_KEY }}
    - name: Install SDL
      run: brew install sdl2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  ubuntu-bionic:
    container: 
      image: vapor/swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install SDL
      run: apt-get update -y && apt-get install libsdl2-dev
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
