name: Swift

on: [push]

jobs:
  build-macos:
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: Homebrew/actions/git-ssh@master
      with:
        git_user: username
        git_email: username@example.org
        key_name: key_rsa
        key: ${{ secrets.SSH_KEY }}
    - name: Install SDL
      run: brew install sdl2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
